M48
; DRILL file {KiCad 8.0.0} date 2024-05-23T14:19:21-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-23T14:19:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X-457.02Y-225.07
X-456.94Y-204.74
X-456.8Y-38.6
X-456.8Y-128.6
T2
X-462.83Y-257.2
X-451.4Y-257.2
M30
